### ISSUE TITLE
アップロードが出来ないバグ

### ISSUE THREAD

**Issue by EdamAme-x** [ActiveTK/End2End.tech#10]
現在文字化けした文字列が返され、遷移後は白紙です。

![image](https://github.com/ActiveTK/End2End.tech/assets/121654029/1e781208-ba8f-45a9-8673-a9111df93fae)

本番環境でテストをしているのでしょうか？
おそらく環境変数等でパスを調整していないのでそうだと思いますが 危険では？

**Comment by EdamAme-x** [comment]
ちなみに白紙になるのは遷移後がundefinedだからです。

**Comment by ActiveTK** [comment]
私の環境では再現できませんでした。
文字コードの不一致による文字化けは、昨日のコミット https://github.com/ActiveTK/End2End.tech/commit/0af404026ab4bd76c66e8fc8859c5f869c2af500 で修正しているはずですから、ブラウザのキャッシュが原因かもしれません。

**Comment by EdamAme-x** [comment]
了解です。
キャッシュを消し
safari, chromeの二つの環境でもう一度再現出来るか試してみます。

**Comment by EdamAme-x** [comment]
現在確認したところ、 2つの環境では何れも確認されませんでした。
おそらくキャッシュの影響ですね。
