### ISSUE TITLE
タイポグラフィ

### ISSUE THREAD

**Issue by kaminomisosiru** [ActiveTK/End2End.tech#13]
Decryptionに対応する日本語は復号です。(複合は誤りです)
また、用語としては、復号のほうが復号化よりも一般的だと思います。

対象ファイル:

- [scripts/download-loader.php](https://github.com/ActiveTK/End2End.tech/blob/07fba51a4e421ec14f30cdc6d081d5f429103f70/scripts/download-loader.php#L112)
- [public_html/js/download.js](https://github.com/ActiveTK/End2End.tech/blob/07fba51a4e421ec14f30cdc6d081d5f429103f70/public_html/js/download.js#L16)

**Comment by ActiveTK** [comment]
b82acd7d4dee9b2a69cec37a041c1dec5000c5a5 で修正させて頂きました。
