### ISSUE TITLE
ファイルが正しく復号されない (正当性エラー)

### ISSUE THREAD

**Issue by kaminomisosiru** [ActiveTK/End2End.tech#14]
## 問題の内容
txtとjpegの2種類のファイルをアップロードしたところ、jpegの場合に壊れたファイルが復号された。

## 実行環境 

- macOS Ventura 13.5.1（22G90）
- Google Chrome 116.0.5845.140（Official Build） （arm64）

## 再現手順

1. [JPG_Test.jpg](https://ja.wikipedia.org/wiki/%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB:Test.jpg)をアップロードする。 
2. アップロード先[https://end2end.tech/cf0964f53d5b](https://end2end.tech/cf0964f53d5b)からファイルをダウンロードする。

アップロードしたファイルとダウンロードしたファイルのSHA256値は以下の通り (ローカル環境にてshasum -a 256 filenameで計算)

- アップロードファイル: 45acdb74b195a2cd159eb21603c2bb24699e31e01671c2e0dc9f6ae3876da80f  
- ダウンロードファイル: 95f758bf28d2d48783f268fba853a286f6488c1933bdfc077569b3e3b86069f1

**Comment by ActiveTK** [comment]
xhrの結果をテキストとして受け取っていたため、arraybufferとして取得することにより修正しました。
(サーバー上の保管における問題ではないため、過去にアップロードされたファイルは全て利用可能です)。
c41b764bc9295b0dd9b12b8708ff51b9ac865b34
