### ISSUE TITLE
パスワードチェックエラー

### ISSUE THREAD

**Issue by kaminomisosiru** [ActiveTK/End2End.tech#15]
## 問題の内容
ファイルサイズの小さいファイルをパスワードで暗号化してアップロードしたとき、パスワードを入力しなくてもダウンロードインターフェースが立ち上がり、空のファイルをダウンロードできる。

## 実行環境 

- macOS Ventura 13.5.1（22G90）
- Google Chrome 116.0.5845.140（Official Build） （arm64）

## 再現手順

1. ファイルサイズの小さいファイル（1バイトのtxtファイルなど）をパスワードで暗号化してアップロードする。 
2. アップロード先[https://end2end.tech/f31664f5e4df](https://end2end.tech/f31664f5e4df)にて、パスワードを入力せず「ファイルをダウンロード」をクリックする。
3. ダウンローダが起動し、空のファイル(サイズ0のファイル)がダウンロードされる。
4. (Step 2で適当なパスワードを入力した場合もダウンローダが起動する)

上記リンクでは中身が「1」のテキストファイルをアップロードした。パスワード「qwertyuiop」を入力してダウンロードすることで元のファイルを入手できる。

意味のあるファイルがダウンロードされるわけではないが、意図した動作ではないと思われる。

**Comment by ActiveTK** [comment]
ファイルが極端に小さい場合においては、どのようなパスワードにおいてもデータの整合性が取れてしまう場合があります。
b28154415685719aea0f6b1d5ead6a84547801f7 においてファイルを暗号化する場合には自動的にData URIに置き換える処理を追加し、暗号化データは最低でも数十文字以上となるように修正しました。

**Comment by kaminomisosiru** [comment]
> ファイルが極端に小さい場合においては、どのようなパスワードにおいてもデータの整合性が取れてしまう場合があります。

上記の問題が起きている原因はどこにあるのでしょうか。
