### ISSUE TITLE
提案: 改ざん検知機能付き共通鍵暗号の利用

### ISSUE THREAD

**Issue by kaminomisosiru** [ActiveTK/End2End.tech#16]
AES-CBCは暗号学的な改ざん検知機能がないため、アップロードした暗号化ファイルがデータベース管理者等に改ざんされたとしても、ダウンロード時にそれを検知することができません。
AES-CBCのかわりに、AES-GCMやChaCha20-poly1305等の改ざん検知機能付き共通鍵暗号の利用を提案します。

**Comment by ActiveTK** [comment]
サーバー管理者がプログラム本体を編集できる以上、暗号学的な改ざん検知機能を持つ暗号方式を利用することに意味はないのではないでしょうか。
代替としてダウンロードページにおけるハッシュ値表示を行っているため、送付先の相手に事前にハッシュ値を共有しておけば、ファイルの改竄は判別が可能です。
