### ISSUE TITLE
アップロード後の表示について

### ISSUE THREAD

**Issue by EdamAme-x** [ActiveTK/End2End.tech#2]
![image](https://github.com/ActiveTK/End2End.tech/assets/121654029/2fd549f0-8ad1-4fa3-ae82-184698d37e6c)

現状このような感じですが、flex-colを用いて縦形式にするのがUI的に優れていると思います。

レスポンシブにも当たるので

**Comment by ActiveTK** [comment]
縦形式とはどのようなUIを意味するのでしょうか？
一応、各項目のheightを40pxで固定して、潰れないようにしてみました。
cd85a6c81f7ce41e7d573c983915676dd05160d8

**Comment by EdamAme-x** [comment]
flex-colについて学べば分かると思います
