### ISSUE TITLE
バグの報告

### ISSUE THREAD

**Issue by EdamAme-x** [ActiveTK/End2End.tech#4]
https://api.end2end.tech
相対パスの指定をミスっていると思います🤔
footer.phpの読み込みでエラー吐いてますね

**Comment by EdamAme-x** [comment]
このissueは解決後も使えると思うので残しましょう

**Comment by ActiveTK** [comment]
ご指摘有難うございます。
修正させて頂きました。

**Comment by ooitanojohn** [comment]
![image](https://github.com/ActiveTK/End2End.tech/assets/71388489/0057682a-5f53-4ca6-a065-efce3333bc69)
チェックボックス選択すると要素が隠れてtorからのチェックボックスが押せなくなりますよ～
