### ISSUE TITLE
ローカルでのセットアップ方法について

### ISSUE THREAD

**Issue by itta611** [ActiveTK/End2End.tech#5]
本番環境に特化した設定が多く見受けられ、ローカル環境でのセットアップが困難です..
OSS化したいのであれば、セットアップの方法を README に書いておくと良いかもしれません。

具体的には、以下のようなコードが問題となっています。

```index.php
require_once( "/home/activetk3/Config.php" );
```
コンテナ化をするなどして、環境に依存しない形にするとよいかもしれません。

また、開発環境では https:// へのリダイレクトは回避したほうがいいので、例えばサーバーの設定ファイルや、Cloudflareの設定項目などを使い、コードではない形で設定したほうがいいです。

**Comment by nakasyou** [comment]
同意です。

`/home/activetk3/Config.php`の内容の例をあげたり、このパスを環境変数にしたりするのはどうでしょうか。

**Comment by ActiveTK** [comment]
Issue有難うございます。

リポジトリ直下にConfig.phpを作成し、ドメイン名の設定、MySQLの設定、TLSの有無などを設定できるようにしたいと思います。

**Comment by ActiveTK** [comment]
b227fd01c76082430758712e7032b91fc6c30dcd でConfig.phpを追加しました。
追加のドキュメンテーションは、README.mdに後ほど追加します。

**Comment by itta611** [comment]
参考までに、環境によって異なるDB情報などは、環境変数（.env）を利用するのが一般的だったりします！

**Comment by ActiveTK** [comment]
> 参考までに、環境によって異なるDB情報などは、環境変数（.env）を利用するのが一般的だったりします！

サーバー代金に対するディスク容量の都合上、VPSではなくレンタルサーバーを利用しています。
そのため、環境変数を自由に設定できず、`wp-config.php`のようにdefineで対応する形を取っています。

**Comment by itta611** [comment]
PHPが動作する環境があるのならレンタルサーバーであろうと環境変数は使用できるはずです。（原理は.envファイルを読み込んでいるだけなので..）
今回 define で定義するようにしたということであれば、わざわざ .env を使うように書き直すほどのものはないですが、OSSではよく利用されますので別のプロジェクトではそちらを使うことをおすすめします。
