### ISSUE TITLE
暗号化したときのデータが文字列になっている

### ISSUE THREAD

**Issue by nakasyou** [ActiveTK/End2End.tech#6]
暗号化したときのデータが文字列になっています。

理由は、Base64にソルトなどをつけた形になっているからです。

このデータをバイナリ化してアップロードすれば、ディスク使用効率が高くなると考えられます。

**Comment by ActiveTK** [comment]
暗号化したデータは、以下のように「ソルト,IV,暗号データ」という形式で保存されています。

`bd2e7a36a458fe79536327b1c9dbcc8e,a033960a5126572048542cd7b601ced7,EBzhB9ext2CC2Z8ZPj0thuASHgVg7MM6sOd9n/EFzOQ=`

この暗号データは`CryptoJS.AES.encrypt`という関数を用いてAESで暗号化した結果そのものであり、base64でエンコードしている訳ではありません(そのため、`z`のような文字も使用されています)。

外部のライブラリを用いて、JavaScriptでファイルを圧縮することで無理やりバイナリ化することはできますが、クライアント側の端末はサーバーに比べると性能が劣っていることも考慮し、本サービスにおいてはサーバー側でデータを圧縮して保存しています。
https://github.com/ActiveTK/End2End.tech/blob/main/api/upload.php#L93

故に、既にサーバー側で圧縮して保存しているため、ディスクの使用効率は十分高いものであると考えられます。
