### ISSUE TITLE
最大ダウンロード回数に小数を指定できてしまう

### ISSUE THREAD

**Issue by e6nlaq** [ActiveTK/End2End.tech#8]
```bash
curl https://api.end2end.tech/upload -X POST -F file=@hoge.txt -F 'setLimitDownload=on' -F 'maxDownloadCount=1.7'
```

上記のように、APIで`maxDownloadCount`の項目が小数の場合で叩いても正常にアップロードできてしまいます。

通常のWeb版では指定できないので、おそらくバグかと思われます。

もし万が一仕様だったら、APIドキュメントに明確な仕様を書いた方がよいかもしれません。

**Comment by ActiveTK** [comment]
最大ダウンロード回数には、非負整数のみ指定できる仕様としています。
9bce1cf2a23c95fbeb12ec55a5be9cefae17d286 でエラーを出力するように修正させて頂きました。

**Comment by ActiveTK** [comment]
念のため追記です。curlにおけるPOSTオプションの指定に、引用符は必要ありませんでした。
検証の際には、以下のコマンドを試して下さい。
`curl https://api.end2end.tech/upload -X POST -F file=@hoge.txt -F setLimitDownload=on -F maxDownloadCount=1.7`
